"""Schemas and State Definitions for the Parallel Research and Publishing Graph."""

import operator
from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field
from langgraph.graph import MessagesState


class ApprovalDecision(BaseModel):
    """Structured decision returned by the Approver Agent."""

    approved: bool = Field(
        description="True if the research plan is sound, comprehensive, and ready for dispatch. False if it needs revision."
    )
    critique: str = Field(
        description="Specific feedback, corrections, or missing areas that need improvement if not approved, or approval confirmation."
    )
    suggested_queries: List[str] = Field(
        default_factory=list,
        description="Suggested refined search queries for DuckDuckGo research."
    )


class ResearchState(MessagesState, total=False):
    """LangGraph state representation for the Parallel Research, Critic, and Publisher Graph.

    State fields:
    - topic: Primary subject or query to research and publish.
    - plan: Detailed research plan and outline generated by planner.
    - plan_critique: Feedback provided by the Approver Agent during review.
    - plan_approved: Boolean flag set by the Approver Agent.
    - plan_revision_count: Number of revisions completed.
    - research_queries: List of DuckDuckGo queries to dispatch.
    - research_notes: Accumulated web search findings reduced via `operator.add`.
    - draft: Initial comprehensive article/report draft produced by synthesizer.
    - fact_critique: Findings from the Fact Critic evaluating evidence and claims.
    - style_critique_1: Tone and readability critique from Style Critic 1.
    - style_critique_2: Structure, polish, and actionable takeaway review from Style Critic 2.
    - final_output: Final synthesized, fact-checked, style-refined published article.
    """

    topic: str
    plan: str
    plan_critique: str
    plan_approved: bool
    plan_revision_count: int
    research_queries: List[str]
    research_notes: Annotated[List[str], operator.add]
    draft: str
    fact_critique: str
    style_critique_1: str
    style_critique_2: str
    final_output: str


class ResearchRequest(BaseModel):
    """Request payload to initiate the parallel research graph."""

    topic: str = Field(..., description="Topic or question to research and publish.")
    thread_id: Optional[str] = Field(default=None, description="Optional thread identifier for state persistence.")
    max_search_results: int = Field(default=3, ge=1, le=10, description="Max search results per DuckDuckGo query.")
    max_plan_revisions: int = Field(default=2, ge=1, le=5, description="Max revision cycles allowed for the Approver Agent.")


class ResearchResponse(BaseModel):
    """Response payload containing the full pipeline outputs."""

    topic: str
    plan: str
    plan_approved: bool
    draft: str
    fact_critique: str
    style_critique_1: str
    style_critique_2: str
    final_output: str
    research_notes_count: int
