"""Centralized LLM Factory utilizing Groq."""

import logging
from typing import Optional
from langchain_groq import ChatGroq
from app.core.config import settings

logger = logging.getLogger(__name__)


def get_llm(
    model_name: Optional[str] = None,
    temperature: Optional[float] = None,
    max_tokens: Optional[int] = None,
    max_retries: Optional[int] = None,
) -> ChatGroq:
    """Instantiates and returns a configured ChatGroq instance.

    Args:
        model_name: The Groq model identifier (defaults to settings.DEFAULT_MODEL).
        temperature: Sampling temperature (defaults to settings.LLM_TEMPERATURE).
        max_tokens: Maximum number of completion tokens generated by the model.
        max_retries: Maximum number of retries on API errors.

    Returns:
        Configured ChatGroq instance.
    """
    model = model_name or settings.DEFAULT_MODEL
    temp = temperature if temperature is not None else settings.LLM_TEMPERATURE
    retries = max_retries if max_retries is not None else settings.LLM_MAX_RETRIES
    api_key = settings.GROQ_API_KEY.strip()

    if not api_key:
        logger.warning("GROQ_API_KEY is not set. LLM invocations may fail unless a mock or valid key is provided.")

    return ChatGroq(
        model_name=model,
        temperature=temp,
        max_tokens=max_tokens,
        groq_api_key=api_key or "mock-key",
        max_retries=retries,
    )
